### ISSUE TITLE
make plural easy

### ISSUE THREAD

**Issue by evan361425** [evan361425/flutter-arb-glue#1]
## Purpose

Plural is still hard to use when value is too long

## Spec

```yaml
myButton:
- {0: Empty items, other: Edit items}
- Edit item if exist
- count: {type: int, plural: true}
```
