### ISSUE TITLE
multiple context in one file

### ISSUE THREAD

**Issue by evan361425** [evan361425/flutter-arb-glue#2]
## Purpose

Same file can have multiple prefix

## Spec

```yaml
menu:
  "@@context": menu
  title: 'Title of menu'
  product:
    "@@context": product
    title: 'Title of product in menu'
```
